In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ---------- ----------------------------- 3.4/12.7 MB 21.2 MB/s eta 0:00:01
   -------------- ------------------------- 4.5/12.7 MB 12.8 MB/s eta 0:00:01
   ------------------ --------------------- 5.8/12.7 MB 9.3 MB/s eta 0:00:01
   --------------------- ------------------ 6.8/12.7 MB 8.3 MB/s eta 0:00:01
   ----------------------- ---------------- 7.6/12.7 MB 7.8 MB/s eta 0:00:01
   --------------------------- ------------ 8.7/12.7 MB 7.2 MB/s eta 0:00:01
   ---------------------------- ----------- 9.2/12.7 MB 6.7 MB/s eta 0:00:01
   ------------------------------ --------- 9.7/12.7 MB 6.0 MB/s eta 0:00:01
   -------------------------------- ------- 10.2/12.7 MB 5.5 MB/s eta 0:00:01
   --------------------------------- ------ 10.7/12.7 MB 5.2 MB/s eta 0:00:01
   ------------------------------------ --- 11.5/12.7 MB 5.0 MB/s eta 0:00:01


In [16]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr)
print(type(arr))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [17]:
arr=arr.reshape(3,3)
print(arr)
arr.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [18]:
arr=np.arange(0,11,2).reshape(2,3)
print(arr)

[[ 0  2  4]
 [ 6  8 10]]


In [19]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.zeros((2,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
#identical elements
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
a1=np.array([1,2,3,4,5])
a2=np.array([10,20,30,40,50])
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)
print(a1%a2)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]
[1 2 3 4 5]


In [26]:
print(np.sqrt(a1))
print(np.sign(a1))
print(np.exp(a1))
print(np.sin(a1))

[1.         1.41421356 1.73205081 2.         2.23606798]
[1 1 1 1 1]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [27]:
print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))

3.0
3.0
1.4142135623730951
2.0


In [28]:
a=a1[a1>2]
print(a)

[3 4 5]
